# Generated by Django 2.0.9 on 2018-11-01 18:45

from django.db import migrations, models
import django.db.models.manager
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blogpage',
            managers=[
                ('extra', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='blogpage',
            name='excerpt_ca',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='The page description that will appear under the title.On Entry list, excerpt to be displayed.If this field is not filled, a truncate version of body text will be used.', null=True, verbose_name='Excerpt'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='excerpt_en',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='The page description that will appear under the title.On Entry list, excerpt to be displayed.If this field is not filled, a truncate version of body text will be used.', null=True, verbose_name='Excerpt'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='excerpt_es',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='The page description that will appear under the title.On Entry list, excerpt to be displayed.If this field is not filled, a truncate version of body text will be used.', null=True, verbose_name='Excerpt'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ca',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_es',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ca',
            field=models.CharField(max_length=80, null=True, unique=True, verbose_name='Category name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=80, null=True, unique=True, verbose_name='Category name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es',
            field=models.CharField(max_length=80, null=True, unique=True, verbose_name='Category name'),
        ),
        migrations.AddField(
            model_name='entrypage',
            name='body_ca',
            field=wagtail.core.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='entrypage',
            name='body_en',
            field=wagtail.core.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='entrypage',
            name='body_es',
            field=wagtail.core.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='entrypage',
            name='excerpt_ca',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='The page description that will appear under the title.On Entry list, excerpt to be displayed.If this field is not filled, a truncate version of body text will be used.', null=True, verbose_name='Excerpt'),
        ),
        migrations.AddField(
            model_name='entrypage',
            name='excerpt_en',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='The page description that will appear under the title.On Entry list, excerpt to be displayed.If this field is not filled, a truncate version of body text will be used.', null=True, verbose_name='Excerpt'),
        ),
        migrations.AddField(
            model_name='entrypage',
            name='excerpt_es',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='The page description that will appear under the title.On Entry list, excerpt to be displayed.If this field is not filled, a truncate version of body text will be used.', null=True, verbose_name='Excerpt'),
        ),
    ]
