# Generated by Django 2.1.3 on 2018-12-02 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181101_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='main_color',
        ),
    ]
