# Generated by Django 2.1.8 on 2019-04-18 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181101_1845'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blogpage',
            managers=[
            ],
        ),
    ]
