# Generated by Django 2.0.9 on 2018-11-01 18:42

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailimages', '0021_image_file_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.CharField(blank=True, help_text='Default value. Comma separated values supported for checkboxes.', max_length=255, verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('excerpt', wagtail.core.fields.RichTextField(blank=True, help_text='The page description that will appear under the title.On Entry list, excerpt to be displayed.If this field is not filled, a truncate version of body text will be used.', verbose_name='Excerpt')),
                ('parallax_filter', models.CharField(blank=True, choices=[('filter filter-black', 'filter-black'), ('filter filter-white', 'filter-white'), ('filter filter-blue', 'filter-blue'), ('filter filter-azure', 'filter-azure'), ('filter filter-green', 'filter-green'), ('filter filter-orange', 'filter-orange'), ('filter filter-red', 'filter-red'), ('filter filter-white', 'filter-white'), ('', 'No filter')], default='filter-black', help_text='Filter effect', max_length=30, null=True, verbose_name='Image Filter')),
                ('parallax_size', models.CharField(blank=True, choices=[('parallax-small', 'Small'), ('parallax-medium', 'Medium'), ('parallax-large', 'Large')], default='parallax-small', help_text='Size effect', max_length=30, null=True, verbose_name='Image Size')),
                ('show_search', models.BooleanField(default=False, help_text='Whether a search form will appear in automatically generated menus', verbose_name='Show search in menus')),
                ('menu_icon', models.CharField(blank=True, max_length=60, null=True, verbose_name='Icon Class')),
                ('to_address', models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, verbose_name='to address')),
                ('from_address', models.CharField(blank=True, max_length=255, verbose_name='from address')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('thank_you_text', wagtail.core.fields.RichTextField(blank=True)),
                ('is_modal', models.BooleanField(default=False, help_text='Check it if you want to launch view as modal', verbose_name='Must be modal form')),
                ('header_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Header image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.AddField(
            model_name='formfield',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='wagtail_recaptcha2forms.FormPage'),
        ),
    ]
