# Generated by Django 2.0.9 on 2018-11-01 18:45

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_recaptcha2forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='excerpt_ca',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='The page description that will appear under the title.On Entry list, excerpt to be displayed.If this field is not filled, a truncate version of body text will be used.', null=True, verbose_name='Excerpt'),
        ),
        migrations.AddField(
            model_name='formpage',
            name='excerpt_en',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='The page description that will appear under the title.On Entry list, excerpt to be displayed.If this field is not filled, a truncate version of body text will be used.', null=True, verbose_name='Excerpt'),
        ),
        migrations.AddField(
            model_name='formpage',
            name='excerpt_es',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='The page description that will appear under the title.On Entry list, excerpt to be displayed.If this field is not filled, a truncate version of body text will be used.', null=True, verbose_name='Excerpt'),
        ),
        migrations.AddField(
            model_name='formpage',
            name='thank_you_text_ca',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formpage',
            name='thank_you_text_en',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formpage',
            name='thank_you_text_es',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
