# Generated by Django 2.0.9 on 2018-11-01 18:42

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtaildocs', '0008_document_file_size'),
        ('base', '0001_initial'),
        ('wagtailcore', '0040_page_draft_title'),
        ('blog', '0001_initial'),
        ('wagtailimages', '0021_image_file_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkfields',
            name='link_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.Category', verbose_name='Blog Category'),
        ),
        migrations.AddField(
            model_name='linkfields',
            name='link_document',
            field=models.ForeignKey(blank=True, help_text='Choose an existing document if you want the link to open a document.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
        migrations.AddField(
            model_name='linkfields',
            name='link_page',
            field=models.ForeignKey(blank=True, help_text='Choose an existing page if you want the link to point somewhere inside the CMS.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='homepagecard',
            name='homepage',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_items', to='base.HomePage'),
        ),
        migrations.AddField(
            model_name='homepagecard',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Header image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Header image'),
        ),
        migrations.AddField(
            model_name='basesitesettings',
            name='contact_us',
            field=models.ForeignKey(blank=True, help_text='Choose an existing page if you want the link to point somewhere inside the CMS.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Internal link to contact us page'),
        ),
        migrations.AddField(
            model_name='basesitesettings',
            name='site',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site'),
        ),
        migrations.AddField(
            model_name='standardpagerelatedlink',
            name='standardpage',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_links', to='base.StandardPage'),
        ),
        migrations.AddField(
            model_name='homepagerelatedlink',
            name='homepage',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_links', to='base.HomePage'),
        ),
    ]
