# Generated by Django 2.0.6 on 2018-08-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='url_link',
            field=models.CharField(blank=True, help_text='Relative links are allowed', max_length=255, null=True, verbose_name='Url'),
        ),
    ]
