# Generated by Django 2.0.6 on 2018-09-19 21:13

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_card_url_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='excerpt_ca',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='The page description that will appear under the title.On Entry list, excerpt to be displayed.If this field is not filled, a truncate version of body text will be used.', null=True, verbose_name='Excerpt'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='excerpt_es',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='The page description that will appear under the title.On Entry list, excerpt to be displayed.If this field is not filled, a truncate version of body text will be used.', null=True, verbose_name='Excerpt'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_ca',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title Catalan'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title Spanish'),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='body_ca',
            field=wagtail.core.fields.StreamField([('heading_block', wagtail.core.blocks.StructBlock([('heading_text', wagtail.core.blocks.CharBlock(classname='title', required=True)), ('size', wagtail.core.blocks.ChoiceBlock(blank=True, choices=[('', 'Select a header size'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], help_text='Custom StructBlock that allows the user to select h2 - h4 sizes for headers', required=False))])), ('intro', wagtail.core.blocks.RichTextBlock(icon='pilcrow')), ('paragraph_block', wagtail.core.blocks.RichTextBlock(icon='fa-paragraph', template='blocks/block_paragraph.html')), ('aligned_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('caption', wagtail.core.blocks.CharBlock(required=False)), ('size', wagtail.core.blocks.CharBlock(help_text='It must be defined in wagtail picture redimension tag: width-640, height-480, fill-200x200-c100 or original (which is the default option)', label='Image resize', required=False)), ('alignment', wagtail.core.blocks.ChoiceBlock(choices=[('float-left', 'Wrap left'), ('float-right', 'Wrap right'), ('mx-auto d-block', 'Mid width')])), ('shape', wagtail.core.blocks.ChoiceBlock(choices=[('rounded', 'Rounded Corner'), ('rounded-circle', 'Circle'), ('img-thumbnail', 'Thumbnail'), ('img-fluid', 'Responsive'), (' ', 'No Shape')]))], icon='image', label='Aligned image')), ('aligned_html', wagtail.core.blocks.RawHTMLBlock(icon='code', label='Raw HTML')), ('document', wagtail.documents.blocks.DocumentChooserBlock(icon='doc-full-inverse')), ('block_quote', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock()), ('attribute_name', wagtail.core.blocks.CharBlock(blank=True, help_text='Custom StructBlock that allows the user to attribute a quote to the author', label='e.g. Mary Berry', required=False))])), ('block_parallax', wagtail.core.blocks.StructBlock([('parallax_image', wagtail.images.blocks.ImageChooserBlock()), ('parallax_size', wagtail.core.blocks.ChoiceBlock(choices=[('parallax-small', 'Small'), ('parallax-medium', 'Medium'), ('parallax-large', 'Large')], help_text='Parallax size')), ('parallax_filter', wagtail.core.blocks.ChoiceBlock(choices=[('filter filter-black', 'filter-black'), ('filter filter-white', 'filter-white'), ('filter filter-blue', 'filter-blue'), ('filter filter-azure', 'filter-azure'), ('filter filter-green', 'filter-green'), ('filter filter-orange', 'filter-orange'), ('filter filter-red', 'filter-red'), ('filter filter-white', 'filter-white'), ('', 'No filter')], help_text='Filter effect')), ('display_btndropdown', wagtail.core.blocks.BooleanBlock(default=False, help_text='Display dropdown button', required=False)), ('parallax_content', wagtail.core.blocks.StructBlock([('parallax_head', wagtail.core.blocks.CharBlock(blank=True, classname='title', help_text='You can split the title using "|". It will add small .subtitle class.', label='Head', required=False)), ('parallax_text', wagtail.core.blocks.RichTextBlock(blank=True, label='Text', null=True, required=False)), ('parallax_pro', wagtail.core.blocks.CharBlock(blank=True, label='Pro', null=True, required=False))]))])), ('embed_block', wagtail.embeds.blocks.EmbedBlock(help_text='Insert an embed URL e.g https://www.youtube.com/embed/SGJFWirQ3ks', icon='fa-s15', template='blocks/block_embed.html'))], blank=True, help_text='Content Catalan', null=True, verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='body_es',
            field=wagtail.core.fields.StreamField([('heading_block', wagtail.core.blocks.StructBlock([('heading_text', wagtail.core.blocks.CharBlock(classname='title', required=True)), ('size', wagtail.core.blocks.ChoiceBlock(blank=True, choices=[('', 'Select a header size'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], help_text='Custom StructBlock that allows the user to select h2 - h4 sizes for headers', required=False))])), ('intro', wagtail.core.blocks.RichTextBlock(icon='pilcrow')), ('paragraph_block', wagtail.core.blocks.RichTextBlock(icon='fa-paragraph', template='blocks/block_paragraph.html')), ('aligned_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('caption', wagtail.core.blocks.CharBlock(required=False)), ('size', wagtail.core.blocks.CharBlock(help_text='It must be defined in wagtail picture redimension tag: width-640, height-480, fill-200x200-c100 or original (which is the default option)', label='Image resize', required=False)), ('alignment', wagtail.core.blocks.ChoiceBlock(choices=[('float-left', 'Wrap left'), ('float-right', 'Wrap right'), ('mx-auto d-block', 'Mid width')])), ('shape', wagtail.core.blocks.ChoiceBlock(choices=[('rounded', 'Rounded Corner'), ('rounded-circle', 'Circle'), ('img-thumbnail', 'Thumbnail'), ('img-fluid', 'Responsive'), (' ', 'No Shape')]))], icon='image', label='Aligned image')), ('aligned_html', wagtail.core.blocks.RawHTMLBlock(icon='code', label='Raw HTML')), ('document', wagtail.documents.blocks.DocumentChooserBlock(icon='doc-full-inverse')), ('block_quote', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock()), ('attribute_name', wagtail.core.blocks.CharBlock(blank=True, help_text='Custom StructBlock that allows the user to attribute a quote to the author', label='e.g. Mary Berry', required=False))])), ('block_parallax', wagtail.core.blocks.StructBlock([('parallax_image', wagtail.images.blocks.ImageChooserBlock()), ('parallax_size', wagtail.core.blocks.ChoiceBlock(choices=[('parallax-small', 'Small'), ('parallax-medium', 'Medium'), ('parallax-large', 'Large')], help_text='Parallax size')), ('parallax_filter', wagtail.core.blocks.ChoiceBlock(choices=[('filter filter-black', 'filter-black'), ('filter filter-white', 'filter-white'), ('filter filter-blue', 'filter-blue'), ('filter filter-azure', 'filter-azure'), ('filter filter-green', 'filter-green'), ('filter filter-orange', 'filter-orange'), ('filter filter-red', 'filter-red'), ('filter filter-white', 'filter-white'), ('', 'No filter')], help_text='Filter effect')), ('display_btndropdown', wagtail.core.blocks.BooleanBlock(default=False, help_text='Display dropdown button', required=False)), ('parallax_content', wagtail.core.blocks.StructBlock([('parallax_head', wagtail.core.blocks.CharBlock(blank=True, classname='title', help_text='You can split the title using "|". It will add small .subtitle class.', label='Head', required=False)), ('parallax_text', wagtail.core.blocks.RichTextBlock(blank=True, label='Text', null=True, required=False)), ('parallax_pro', wagtail.core.blocks.CharBlock(blank=True, label='Pro', null=True, required=False))]))])), ('embed_block', wagtail.embeds.blocks.EmbedBlock(help_text='Insert an embed URL e.g https://www.youtube.com/embed/SGJFWirQ3ks', icon='fa-s15', template='blocks/block_embed.html'))], blank=True, help_text='Content Spanish', null=True, verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='excerpt_ca',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='The page description that will appear under the title.On Entry list, excerpt to be displayed.If this field is not filled, a truncate version of body text will be used.', null=True, verbose_name='Excerpt'),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='excerpt_es',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='The page description that will appear under the title.On Entry list, excerpt to be displayed.If this field is not filled, a truncate version of body text will be used.', null=True, verbose_name='Excerpt'),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='title_ca',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title Catalan'),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='title_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title Spanish'),
        ),
    ]
