# Generated by Django 2.0.6 on 2018-09-19 21:13

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recaptcha2forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='excerpt_ca',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='The page description that will appear under the title.On Entry list, excerpt to be displayed.If this field is not filled, a truncate version of body text will be used.', null=True, verbose_name='Excerpt'),
        ),
        migrations.AddField(
            model_name='formpage',
            name='excerpt_es',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='The page description that will appear under the title.On Entry list, excerpt to be displayed.If this field is not filled, a truncate version of body text will be used.', null=True, verbose_name='Excerpt'),
        ),
        migrations.AddField(
            model_name='formpage',
            name='title_ca',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title Catalan'),
        ),
        migrations.AddField(
            model_name='formpage',
            name='title_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title Spanish'),
        ),
    ]
